// @ts-nocheck

/**
 * Auto Generated by orval
 * Do not edit manually.
 * BaseApp Backend API
 * API para el sistema de BaseApp Backend
 */

export interface UserRegistration {
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email?: string;
  password: string;
}

export interface User {
  readonly id: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email?: string;
}

export interface TokenRefresh {
  readonly access: string;
  refresh: string;
}

export interface PatchedUser {
  readonly id?: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username?: string;
  /** @maxLength 254 */
  email?: string;
}

export interface PatchedBillGroupMember {
  readonly id?: number;
  /** @maxLength 255 */
  name?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  bill_group?: number;
}

export interface PatchedBillGroup {
  readonly id?: number;
  /** @maxLength 255 */
  name?: string;
  readonly number_of_members?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  currency?: CurrencyEnum;
}

export interface PatchedBill {
  readonly id?: number;
  /** @maxLength 255 */
  description?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  amount?: string;
  /** If true, the bill is payed for everyone in the bill group (including the payer) */
  payed_for_everyone?: boolean;
  readonly created_at?: string;
  readonly updated_at?: string;
  /** @nullable */
  bill_group?: number | null;
  payed_by?: number;
  payed_for?: number[];
}

export interface EmailTokenObtain {
  email: string;
  password: string;
}

/**
 * * `USD` - Usd
 * `EUR` - Eur
 */
export enum CurrencyEnum {
  USD = "USD",
  EUR = "EUR",
}
export interface BillGroupMember {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  readonly created_at: string;
  readonly updated_at: string;
  bill_group: number;
}

export interface BillGroupDetail {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  readonly number_of_members: string;
  readonly created_at: string;
  readonly updated_at: string;
  currency?: CurrencyEnum;
  bill_group_members: BillGroupMember[];
  bills: BillDetail[];
}

export interface BillGroup {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  readonly number_of_members: string;
  readonly created_at: string;
  readonly updated_at: string;
  currency?: CurrencyEnum;
}

export interface BillDetail {
  readonly id: number;
  /** @nullable */
  bill_group: number | null;
  payed_by: BillGroupMember;
  /** @maxLength 255 */
  description: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  amount: string;
  payed_for: BillGroupMember[];
  /** If true, the bill is payed for everyone in the bill group (including the payer) */
  payed_for_everyone?: boolean;
  readonly created_at: string;
  readonly updated_at: string;
}

export interface Bill {
  readonly id: number;
  /** @maxLength 255 */
  description: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  amount: string;
  /** If true, the bill is payed for everyone in the bill group (including the payer) */
  payed_for_everyone?: boolean;
  readonly created_at: string;
  readonly updated_at: string;
  /** @nullable */
  bill_group: number | null;
  payed_by: number;
  payed_for?: number[];
}
